import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "Param and SearchParams",
  },
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ articleid: string }>;
}) {
  const { articleid } = await params;
  return (
    <>
      <p>This is the new id {articleid}</p>
      {children}
    </>
  );
}
